[package]
name = "zerocopy-lmdb"
version = "0.1.0"
authors = ["Clément Renault <clement@meilisearch.com>"]
edition = "2018"

[dependencies]
bincode = "1.2.0"
libc = "0.2.62"
lmdb-rkv-sys = "0.9.5"
serde = { version = "1.0.101", features = ["derive"] }
zerocopy = "0.2.8"
